//
//  VILocalizedStringKeys.m
//  UITestingPlayground
//
//  Created by Ellen Shapiro (Vokal) on 2/4/14.
//  Copyright (c) 2014 Ellen Shapiro. All rights reserved.
//

#import "VILocalizedStringKeys.h"

@implementation VILocalizedStringKeys

#pragma mark - Login
NSString * const VI_LOGIN_SERVER_FAILURE = @"VI_LOGIN_SERVER_FAILURE";
NSString * const VI_LOGIN_GO_TEXT = @"VI_LOGIN_GO_TEXT";
NSString * const VI_LOGIN_LOGGING_IN_TEXT = @"VI_LOGIN_LOGGING_IN_TEXT";
NSString * const VI_LOGIN_PASSWORD_LENGTH_FAIL_FORMAT = @"VI_LOGIN_PASSWORD_LENGTH_FAIL_FORMAT";
NSString * const VI_LOGIN_USERNAME_MUST_BE_EMAIL =@"VI_LOGIN_USERNAME_MUST_BE_EMAIL";
NSString * const VI_LOGIN_USERNAME_NOT_EMPTY = @"VI_LOGIN_USERNAME_NOT_EMPTY";
NSString * const VI_LOGIN_INCORRECT_PASSWORD = @"VI_LOGIN_INCORRECT_PASSWORD";
NSString * const VI_LOGIN_INCORRECT_USERNAME = @"VI_LOGIN_INCORRECT_USERNAME";
NSString * const VI_LOGIN_SUCCESS = @"VI_LOGIN_SUCCESS";
NSString * const VI_LOGIN_TITLE = @"VI_LOGIN_TITLE";
NSString * const VI_LOGIN_USERNAME_PLACEHOLDER = @"VI_LOGIN_USERNAME_PLACEHOLDER";
NSString * const VI_LOGIN_PASSWORD_PLACEHOLDER = @"VI_LOGIN_PASSWORD_PLACEHOLDER";
@end
